### ISSUE TITLE
Access to Design Group docker image denied

### ISSUE THREAD

**Issue by ia-cahrens** [keith-gamble/example-perspective-component-module#1]
![image](https://github.com/user-attachments/assets/4902a6fb-1e28-4628-8855-3a2d8fdc569a)

It looks like the docker-compose.yml is pointing to a custom image from Design Group: 
![image](https://github.com/user-attachments/assets/47610449-939e-4c72-a41c-a174bd5a23b9)

instead of official Inductive docker images:
![image](https://github.com/user-attachments/assets/29d00036-0615-45b9-a348-d6eb6ca23b4c)

Is this done in order to have the docker image in developer mode for unsigned module files? I see an environment variable `DEVELOPER_MODE: Y` that I don't recognize from the official docker images, and after some googling I found [this repo](https://github.com/design-group/ignition-docker) that describes the use of what I assume is the right docker image (bwdesigngroup/ignition-docker).

**Comment by keith-gamble** [comment]
Good catch, that was supposed to be pointed to a public one (bwdesigngroup/ignition-docker), but accidentally pointed it to a temp one I had set and didn't realize it.

I have switched it to the IA one, however here are some reasons for using `bwdesigngroup/ignition-docker`:
1. Adds a convenience ENV variable for setting developer values, as mentioned above
2. Sets a few general values by default for quicker development setup without having to configure a larger compose file, like `admin:password` for credentials, a scan frequency of 10 seconds, disables QuickStart, etc. etc.

None of those were too critical for now though, so I switched to the official image.
